import React from 'react';
import PropTypes from 'prop-types';
import deburr from 'lodash/deburr';
import Autosuggest from 'react-autosuggest';
import match from 'autosuggest-highlight/match';
import parse from 'autosuggest-highlight/parse';
import TextField from '@material-ui/core/TextField';
import Paper from '@material-ui/core/Paper';
import MenuItem from '@material-ui/core/MenuItem';
import { withStyles } from '@material-ui/core/styles';


export const suggestions = [
  { label: 'Midlothian, VA' },
  { label: 'Ridley Park, PA' },
  { label: 'Johannesberg, CA' },
  { label: 'Sylva, NC' },
  { label: 'Kewwannee, IL' },
  { label: 'Superior, WI' },
  { label: 'Brewster, OH' },
  { label: 'Stillwater, MN' },
  { label: 'Greeley, CO' },
  { label: 'Lyons, IL' },
  { label: 'Danville, VA' },
  { label: 'Rutland, VT' },
  { label: 'Pendleton, SC' },
  { label: 'Waverly, IA' },
  { label: 'Hillsboro, OR' },
  { label: 'Hutchinson, MN' },
  { label: 'Mundelein, IL' },
  { label: 'Sandpoint, ID' },
  { label: 'Gridley, CA' },
  { label: 'Vassalboro, ME' },
  { label: 'Boulder City, NV' },
  { label: 'Jamestown, ND' },
  { label: 'Niagara Falls, NY' },
  { label: 'Clinton, MS' },
  { label: 'Big Bear Lake, CA' },
  { label: 'Clifton Park, NY' },
  { label: 'Wadsworth, OH' },
  { label: 'Woburn, MA' },
  { label: 'Chula Vista, CA' },
  { label: 'Huntingdon, PA' },
  { label: 'West Allis, WI' },
  { label: 'Williamstown, MA' },
  { label: 'Ashburn, VA' },
  { label: 'Indialantic, FL' },
  { label: 'Mulvane, KS' },
  { label: 'Elkhorn, WI' },
  { label: 'Antioch, CA' },
  { label: 'Chesterbrook, PA' },
  { label: 'St. Augustine, FL' },
  { label: 'Staunton, VA' },
  { label: 'Flagler Beach, FL' },
  { label: 'Chadron, NE' },
  { label: 'Bloomfield Hills, MI' },
  { label: 'Blaine, WA' },
  { label: 'Riverton, UT' },
  { label: 'Frostburg, MD' },
  { label: 'Gulf Breeze, FL' },
  { label: 'Provincetown, MA' },
  { label: 'Dalton, GA' },
  { label: 'Round Hill, VA' },
  { label: 'Saint Albans, VT' },
  { label: 'Starkville, MS' },
  { label: 'Milton, DE' },
  { label: 'Middleburg, FL' },
  { label: 'Rock Falls, IL' },
  { label: 'Ripon, WI' },
  { label: 'Plainfield, IL' },
  { label: 'Evanston, IL' },
  { label: 'Vacaville, CA' },
  { label: 'Branson, MO' },
  { label: 'Fayettevill, GA' },
  { label: 'Kyrkbacken, Ven' },
  { label: 'Bloomfield, NJ' },
  { label: 'Corona, CA' },
  { label: 'Huntington, TX' },
  { label: 'Fountain Valley, CA' },
  { label: 'Port Huron, MI' },
  { label: 'Alpine, TX' },
  { label: 'Leavenworth, WA' },
  { label: 'Mount Laurel, NJ' },
  { label: 'Laguna Niguel, CA' },
  { label: 'Aliso Viejo, CA' },
  { label: 'Park City, UT' },
  { label: 'Ellisville, MS' },
  { label: 'Poulsbo, WA' },
  { label: 'Ridgewood, NJ' },
  { label: 'Winamac, IN' },
  { label: 'Tahlequah, OK' },
  { label: 'Janesville, WI' },
  { label: 'Malden, MA' },
  { label: 'Springfield, OH' },
  { label: 'Piedmont, CA' },
  { label: 'New London, CT' },
  { label: 'Chelsea, MA' },
  { label: 'West Warwick, RI' },
  { label: 'Dedham, MA' },
  { label: 'Needham, MA' },
  { label: 'Littleton, NH' },
  { label: 'Pawtucket, RI' },
  { label: 'Farmington, CT' },
  { label: 'Greenfield, MA' },
  { label: 'North Andover, MA' },
  { label: 'Saugus, MA' },
  { label: 'Bedford, MA' },
  { label: 'Greenwich, NY' },
  { label: 'Lisbon, NH' },
  { label: 'Claremont, NH' },
  { label: 'Thief River Falls, MN' },
  { label: 'Cabiao, Nueva Ecija' },
  { label: 'Madison Heights, MI' },
  { label: 'Bloomsburg, PA' },
  { label: 'Newton Falls, OH' },
  { label: 'Lake Havasu City, AZ' },
  { label: 'Fort Madison, IA' },
  { label: 'Clinton, NJ' },
  { label: 'Kenmore, WA' },
  { label: 'Haverhill, MA' },
  { label: 'Good Hope, IL' },
  { label: 'Mechanic Falls, ME' },
  { label: 'Arden-Arcade, CA' },
  { label: 'Forest City, NC' },
  { label: 'O\'Fallon, MO' },
  { label: 'Albemarle, NC' },
  { label: 'Citrus Heights, CA' },
  { label: 'Dubuque, IA' },
  { label: 'Wasilla, AK' },
  { label: 'Olive Branch, MS' },
  { label: 'Bartlesville, OK' },
  { label: 'Bartlett, TN' },
  { label: 'Hunt Valley, MD' },
  { label: 'Rockdale, TX' },
  { label: 'Rio Rancho, NM' },
  { label: 'Gaithersburg, MD' },
  { label: 'Lincolnville, ME' },
  { label: 'Rockford, MI' },
  { label: 'Carlisle, PA' },
  { label: 'Medianeira, PR' },
  { label: 'St Joseph, MI' },
  { label: 'Lanoka Harbor, NJ' },
  { label: 'Titusville, FL' },
  { label: 'Hastings, NE' },
  { label: 'Newton, NJ' },
  { label: 'Chillicothe, MO' },
  { label: 'Chanute, KS' },
  { label: 'Long Island, NY' },
  { label: 'El Cajon, CA' },
  { label: 'Cedartown, GA' },
  { label: 'Sewickley, PA' },
  { label: 'Oswego, NY' },
  { label: 'Lewistown, MT' },
  { label: 'Ambler, PA' },
  { label: 'Bainbridge, GA' },
  { label: 'Basking Ridge, NJ' },
  { label: 'Avon, CT' },
  { label: 'Mechanicsburg, PA' },
  { label: 'Mansfield, TX' },
  { label: 'Sayville, NY' },
  { label: 'Harrogate, TN' },
  { label: 'Howard, OH' },
  { label: 'Nantucket, MA' },
  { label: 'Morehead, KY' },
  { label: 'Lake Forest, CA' },
  { label: 'Keller, TX' },
  { label: 'Camarillo, CA' },
  { label: 'Garden City, MI' },
  { label: 'Brier, WA' },
  { label: 'Washington, MO, United States' },
  { label: 'Ruidoso, NM' },
  { label: 'Montecito, CA' },
  { label: 'Middletown, OH' },
  { label: 'Clinton Township, MI' },
  { label: 'Gainesville, VA' },
  { label: 'Glenwood Springs, CO' },
  { label: 'Dover, OH' },
  { label: 'Flemington, NJ' },
  { label: 'Niantic, CT' },
  { label: 'Hinsdale, IL' },
  { label: 'Vernon, NJ' },
  { label: 'West Lafayette, IN' },
  { label: 'Selden, NY' },
  { label: 'Cartersville, GA' },
  { label: 'Iowa Falls, IA' },
  { label: 'Lake Elsinore, CA' },
  { label: 'Ada, OK' },
  { label: 'Hoffman Estates, IL' },
  { label: 'Worland, WY' },
  { label: 'Toms River, NJ' },
  { label: 'Tecumseh, OK' },
  { label: 'Satellite Beach, FL' },
  { label: 'Mesquite, NV' },
  { label: 'Centerville, UT' },
  { label: 'Muncie, IN' },
  { label: 'Cedarhurst, NY' },
  { label: 'Marshall, IL' },
  { label: 'Spearville, KS' },
  { label: 'Wheaton, IL' },
  { label: 'Cedarburg, WI' },
  { label: 'Woodstock, VA' },
  { label: 'Odessa, FL' },
  { label: 'Cadiz, KY' },
  { label: 'Cannon Falls, MN' },
  { label: 'Farmingdale, NY' },
  { label: 'New Richmond, WI' },
  { label: 'Discovery Bay, CA' },
  { label: 'Spring Hill, TN' },
  { label: 'California, MD' },
  { label: 'New Eagle, PA' },
  { label: 'Barnstable, MA' },
  { label: 'Dixon, IL' },
  { label: 'Levittown, PA' },
  { label: 'Acton, MA' },
  { label: 'Magnolia, AR' },
  { label: 'Greenwood, IN' },
  { label: 'La Grange Park, IL' },
  { label: 'Brentwood, TN' },
  { label: 'Port St Joe, FL' },
  { label: 'Beverly, MA' },
  { label: 'Gunnison, CO' },
  { label: 'High Ridge, MO' },
  { label: 'Berwick, VIC' },
  { label: 'Upper Marlboro, MD' },
  { label: 'Hanscom AFB, MA' },
  { label: 'Seagoville, TX' },
  { label: 'Canoga Park, CA' },
  { label: 'Lock Haven, PA' },
  { label: 'Fairplay, CO' },
  { label: 'Lunenburg, MA' },
  { label: 'Shelby, NC' },
  { label: 'Snellville, GA' },
  { label: 'Spanish Fork, UT' },
  { label: 'Pittsfield, IL' },
  { label: 'Pooler, GA' },
  { label: 'Rincon, GA' },
  { label: 'Elizabeth City, NC' },
  { label: 'Germantown, WI' },
  { label: 'Harrison, AR' },
  { label: 'Richland, WA' },
  { label: 'Yardley, PA' },
  { label: 'Gresham, OR' },
  { label: 'Perry, GA' },
  { label: 'Mariana, MG' },
  { label: 'Mesquite, TX' },
  { label: 'Foster City, CA' },
  { label: 'Newnan, GA' },
  { label: 'Westcliffe, CO' },
  { label: 'Cave Creek, AZ' },
  { label: 'Kent, OH' },
  { label: 'Effingham, IL' },
  { label: 'Stockholm, ME' },
  { label: 'Willoughby, OH' },
  { label: 'Hopkins, MN' },
  { label: 'Fowler, IN' },
  { label: 'Beach park, IL' },
  { label: 'Bethel, AK' },
  { label: 'Downey, CA' },
  { label: 'Catonsville, MD' },
  { label: 'Blackfoot, ID' },
  { label: 'Farmington, UT' },
  { label: 'Eastsound, WA' },
  { label: 'Lakewood Township, NJ' },
  { label: 'Edmond, OK' },
  { label: 'Walden, NY' },
  { label: 'Buckeye, AZ' },
  { label: 'Dayton, NV' },
  { label: 'Moberly, MO' },
  { label: 'Putnam, CT' },
  { label: 'Tipton, CA' },
  { label: 'Winslow, AZ' },
  { label: 'Huntsville, TX' },
  { label: 'Saint Charles, IL' },
  { label: 'Parkville, MD' },
  { label: 'Evans, GA' },
  { label: 'Kingston, MA' },
  { label: 'Cheboygan, MI' },
  { label: 'Garberville, CA' },
  { label: 'Dwight, IL' },
  { label: 'Farmingville, NY' },
  { label: 'Wylie, TX' },
  { label: 'Sinclairville, NY' },
  { label: 'Telford, PA' },
  { label: 'Dublin, TX' },
  { label: 'Tewksbury, MA' },
  { label: 'Keene, NH' },
  { label: 'Conneaut, OH' },
  { label: 'Coventry, RI' },
  { label: 'Brownsburg, IN' },
  { label: 'Corvallis, OR' },
  { label: 'Covington, LA' },
  { label: 'Riverdale, NJ' },
  { label: 'Seal Beach, CA' },
  { label: 'Eagle River, AK' },
  { label: 'Highland Charter Township, MI' },
  { label: 'Harpers Ferry, WV' },
  { label: 'Jacksonville, AL' },
  { label: 'Paris, KY' },
  { label: 'Milwaukie, OR' },
  { label: 'Wau, South Sudan' },
  { label: 'Elizabethton, TN' },
  { label: 'Mount Pleasant, TX' },
  { label: 'Hot Springs, AR' },
  { label: 'South Beloit, Il' },
  { label: 'Hell, MI' },
  { label: 'Pottsville, PA' },
  { label: 'Quincy, IL' },
  { label: 'Brentwood, CA' },
  { label: 'Marion, IL' },
  { label: 'Largo, FL' },
  { label: 'Ironton, OH' },
  { label: 'West Orange, NJ' },
  { label: 'Pinedale, WY' },
  { label: 'Los Santos, NV' },
  { label: 'Rome, GA' },
  { label: 'Wenatchee, WA' },
  { label: 'Denison, IA' },
  { label: 'Kansas City, KS' },
  { label: 'Commerce, MI' },
  { label: 'Helena, AR' },
  { label: 'Poplar Bluff, MO' },
  { label: 'Torup, Halsnæs' },
  { label: 'Attleboro, MA' },
  { label: 'Gilbert, AZ' },
  { label: 'Ortonville, MI' },
  { label: 'Breckenridge,TX' },
  { label: 'Wickett, TX' },
  { label: 'Everett, MA' },
  { label: 'Ho-Ho-Kus, NJ' },
  { label: 'Eatontown, NJ' },
  { label: 'Wailuku, HI' },
  { label: 'Townsend, MT' },
  { label: 'St. Cloud, MN' },
  { label: 'Safety Harbor, FL' },
  { label: 'Garden City, NY' },
  { label: 'Cowpens, SC' },
  { label: 'Elkton, VA' },
  { label: 'Meridian, MS' },
  { label: 'Lemon Grove, CA' },
  { label: 'Shaodong, Hunan' },
  { label: 'Arcadia, CA' },
  { label: 'Alameda, CA' },
  { label: 'Northport, AL' },
  { label: 'Jefferson City, MO' },
  { label: 'Gastonia, NC' },
  { label: 'Springfield, VT' },
  { label: 'Willow Grove, PA' },
  { label: 'Sugar Land, TX' },
  { label: 'Colton, CA' },
  { label: 'Lancaster, SC' },
  { label: 'Framingham, MA' },
  { label: 'Anthem, AZ' },
  { label: 'Truckee, CA' },
  { label: 'Elkland, PA' },
  { label: 'Elmira, NY' },
  { label: 'Grover Beach, CA' },
  { label: 'Roxboro, NC' },
  { label: 'Williamsburg, KY' },
  { label: 'Croydon, PA' },
  { label: 'Pleasant Hill, CA' },
  { label: 'Knightdale, NC' },
  { label: 'Auburn, CA' },
  { label: 'Gatlinburg, TN' },
  { label: 'Burlington, MA' },
  { label: 'Leesburg, VA' },
  { label: 'Fall River, MA' },
  { label: 'Apple Valley, MN' },
  { label: 'Pawling, NY' },
  { label: 'Loganville, GA' },
  { label: 'Alliance, OH' },
  { label: 'Cumberland, ME' },
  { label: 'Metuchen, NJ' },
  { label: 'South Portland, ME' },
  { label: 'Crawfordsville, IN' },
  { label: 'Jerseyville, IL' },
  { label: 'Rome, NY' },
  { label: 'Waunakee, WI' },
  { label: 'Maysville, KY' },
  { label: 'Escondido, CA' },
  { label: 'Bisbee, AZ' },
  { label: 'Forney, TX' },
  { label: 'Laporte, CO' },
  { label: 'Southaven, MS' },
  { label: 'Columbus, NE' },
  { label: 'Villa Rica, GA' },
  { label: 'Rosholt, SD' },
  { label: 'Burbank, CA' },
  { label: 'Washington, NC' },
  { label: 'Winfield, AL' },
  { label: 'Vidalia, GA' },
  { label: 'Brookhaven, GA' },
  { label: 'Leander, TX' },
  { label: 'Kingston, WA' },
  { label: 'Pleasantville, NY' },
  { label: 'Stuart, FL' },
  { label: 'Baraboo, WI' },
  { label: 'Thiensville, WI' },
  { label: 'Floyd, VA' },
  { label: 'San Leandro, CA' },
  { label: 'Vista, CA' },
  { label: 'Parsons, KS' },
  { label: 'West Monroe, LA' },
  { label: 'Bothell, WA' },
  { label: 'Hay River, NT' },
  { label: 'Oxford, NC' },
  { label: 'Monrovia, CA' },
  { label: 'Wilmington, OH' },
  { label: 'Kennesaw, GA' },
  { label: 'Edgewood, KY' },
  { label: 'Williamston, NC' },
  { label: 'Woodland Park, CO' },
  { label: 'Lander, WY' },
  { label: 'Tullahoma, TN' },
  { label: 'Greenville, PA' },
  { label: 'Galax, VA' },
  { label: 'Temple Hills, MD' },
  { label: 'Tracy, CA' },
  { label: 'Palestine, TX' },
  { label: 'Severna Park, MD' },
  { label: 'Clarksville, IN' },
  { label: 'Yellow Springs, OH' },
  { label: 'Benton, LA' },
  { label: 'Georgetown, KY' },
  { label: 'Weston, FL' },
  { label: 'Evanston, WY' },
  { label: 'Lemont, IL' },
  { label: 'Payson, UT' },
  { label: 'Canyon Lake, CA' },
  { label: 'Burnsville, MN' },
  { label: 'Granby, CT' },
  { label: 'Los Alamos, NM' },
  { label: 'Bremen, KY' },
  { label: 'Greenfield, IN' },
  { label: 'Wethersfield, CT' },
  { label: 'Manchester, TN' },
  { label: 'Plainsboro, NJ' },
  { label: 'Rochester, PA' },
  { label: 'Downers Grove, IL' },
  { label: 'Valley View, TX' },
  { label: 'Susanville, CA' },
  { label: 'Camdenton, MO' },
  { label: 'Vernon Hills, IL' },
  { label: 'Castro Valley, CA' },
  { label: 'Mount Pleasant, SC' },
  { label: 'Whitwell, TN' },
  { label: 'Granbury, TX' },
  { label: 'Hannibal, MO' },
  { label: 'Orange beach, AL' },
  { label: 'Bernalillo, NM' },
  { label: 'Iba, Zambales' },
  { label: 'Charles Town, WV' },
  { label: 'Abington, MA' },
  { label: 'North Wales, PA' },
  { label: 'Chariton, IA' },
  { label: 'Chillicothe, OH' },
  { label: 'East Hampton, NY' },
  { label: 'Beaufort, SC' },
  { label: 'Smyrna, GA' },
  { label: 'Franklin, NC' },
  { label: 'Cooper City, FL' },
  { label: 'Palmetto, FL' },
  { label: 'Martin, TN' },
  { label: 'Fort Lee, NJ' },
  { label: 'Greene, NY' },
  { label: 'Simpsonville, SC' },
  { label: 'Edremit, Balikesir' },
  { label: 'Worthington, OH' },
  { label: 'Manhattan Beach, CA' },
  { label: 'Lexington, MA' },
  { label: 'Robinson, IL' },
  { label: 'Tualtin,  OR' },
  { label: 'Malibu, CA' },
  { label: 'Cambridge, OH' },
  { label: 'Owasso, OK' },
  { label: 'Broomfield, CO' },
  { label: 'Glendale, AZ' },
  { label: 'Indiana, PA, USA' },
  { label: 'Buxton, Guyana' },
  { label: 'Sedona, AZ' },
  { label: 'Lansdale, PA' },
  { label: 'Rushsylvania, OH' },
  { label: 'Ellicott City, MD' },
  { label: 'Homestead, FL' },
  { label: 'Lucedale, MS' },
  { label: 'Clarksburg, WV' },
  { label: 'Scottsboro, AL' },
  { label: 'Ellensburg, WA' },
  { label: 'Lewisville, TX' },
  { label: 'Delaware, OH' },
  { label: 'Ballentine, NC' },
  { label: 'Amityville, NY' },
  { label: 'Cranberry Township, PA' },
  { label: 'Fennimore, WI' },
  { label: 'Gros-Morne, Haiti' },
  { label: 'Morgan City, LA' },
  { label: 'Medina, OH' },
  { label: 'Clarion, PA' },
  { label: 'Hailey, ID' },
  { label: 'Anniston, AL' },
  { label: 'Jacksboro, TN' },
  { label: 'Baker City, OR' },
  { label: 'Hornell, NY' },
  { label: 'Waukegan, IL' },
  { label: 'Akron, OH' },
  { label: 'Albuquerque, NM' },
  { label: 'Anaheim, CA' },
  { label: 'Anchorage, AK' },
  { label: 'Arlington, VA' },
  { label: 'Atlanta, GA' },
  { label: 'Austin, TX' },
  { label: 'Bakersfield, CA' },
  { label: 'Baltimore, MD' },
  { label: 'Baton Rouge, LA' },
  { label: 'Birmingham, AL' },
  { label: 'Boise, ID' },
  { label: 'Boston, MA' },
  { label: 'Brookhaven, NY' },
  { label: 'Buffalo, NY' },
  { label: 'Charlotte, NC' },
  { label: 'Chesapeake, VA' },
  { label: 'Chicago, IL' },
  { label: 'Cincinnati, OH' },
  { label: 'Cleveland, OH' },
  { label: 'Colorado Springs, CO' },
  { label: 'Columbus, OH' },
  { label: 'Corpus Christi, TX' },
  { label: 'Dallas, TX' },
  { label: 'Denver, CO' },
  { label: 'Des Moines, IA' },
  { label: 'Detroit, MI' },
  { label: 'Durham, NC' },
  { label: 'El Paso, TX' },
  { label: 'Fort Wayne, IN' },
  { label: 'Fort Worth, TX' },
  { label: 'Fremont, CA' },
  { label: 'Fresno, CA' },
  { label: 'Garland, TX' },
  { label: 'Glendale, CA' },
  { label: 'Grand Rapids, MI' },
  { label: 'Greensboro, NC' },
  { label: 'Hempstead, NY' },
  { label: 'Hialeah, FL' },
  { label: 'Honolulu, HI' },
  { label: 'Houston, TX' },
  { label: 'Huntington, WV' },
  { label: 'Huntington Beach, CA' },
  { label: 'Indianapolis, IN' },
  { label: 'Irving, TX' },
  { label: 'Islip, NY' },
  { label: 'Jackson, MS' },
  { label: 'Jacksonville, FL' },
  { label: 'Jersey City, NJ' },
  { label: 'Kansas City, MO' },
  { label: 'Las Vegas, NV' },
  { label: 'Lincoln, NE' },
  { label: 'Little Rock, AR' },
  { label: 'Long Beach, CA' },
  { label: 'Los Angeles, CA' },
  { label: 'Louisville, KY' },
  { label: 'Lubbock, TX' },
  { label: 'Madison, WI' },
  { label: 'Memphis, TN' },
  { label: 'Mesa, AZ' },
  { label: 'Miami, FL' },
  { label: 'Milwaukee, WI' },
  { label: 'Minneapolis, MN' },
  { label: 'Mobile, AL' },
  { label: 'Modesto, CA' },
  { label: 'Montgomery, AL' },
  { label: 'New Orleans, LA' },
  { label: 'New York, NY' },
  { label: 'Newark, NJ' },
  { label: 'Norfolk, VA' },
  { label: 'Oakland, CA' },
  { label: 'Oklahoma City, OK' },
  { label: 'Omaha, NE' },
  { label: 'Orlando, FL' },
  { label: 'Oyster Bay, NY' },
  { label: 'Paradise, NV' },
  { label: 'Philadelphia, PA' },
  { label: 'Phoenix, AZ' },
  { label: 'Pittsburgh, PA' },
  { label: 'Plano, TX' },
  { label: 'Portland, OR' },
  { label: 'Raleigh, NC' },
  { label: 'Reno, NV' },
  { label: 'Richmond, VA' },
  { label: 'Riverside, CA' },
  { label: 'Rochester, NY' },
  { label: 'Sacramento, CA' },
  { label: 'Saint Louis, MO' },
  { label: 'Saint Paul, MN' },
  { label: 'Saint Petersburg, FL' },
  { label: 'Salt Lake City, UT' },
  { label: 'San Antonio, TX' },
  { label: 'San Bernardino, CA' },
  { label: 'San Diego, CA' },
  { label: 'San Francisco, CA' },
  { label: 'San Jose, CA' },
  { label: 'Santa Ana, CA' },
  { label: 'Scottsdale, AZ' },
  { label: 'Seattle, WA' },
  { label: 'Shreveport, LA' },
  { label: 'Spokane, WA' },
  { label: 'Stockton, CA' },
  { label: 'Tacoma, WA' },
  { label: 'Tampa, FL' },
  { label: 'Toledo, OH' },
  { label: 'Tucson, AZ' },
  { label: 'Tulsa, OK' },
  { label: 'Virginia Beach, VA' },
  { label: 'Washington, DC' },
  { label: 'Wichita, KS' },
  { label: 'Winston-Salem, NC' },
  { label: 'Yonkers, NY' },
  { label: 'Wilkes-Barre, PA' },
  { label: 'Streator, IL' },
  { label: 'Imperial, CA' },
  { label: 'Knoxville, TN' },
  { label: 'Burlington, VT' },
  { label: 'Watertown, SD' },
  { label: 'Wheeling, WV' },
  { label: 'Boynton Beach, FL' },
  { label: 'Stamford, CT' },
  { label: 'Hilton Head Island, SC' },
  { label: 'Yorktown, VA' },
  { label: 'Savannah, GA' },
  { label: 'Streamwood, IL' },
  { label: 'Fairmont, WV' },
  { label: 'Weslaco, TX' },
  { label: 'Russellville, AR' },
  { label: 'Stevens Point, WI' },
  { label: 'Santa Fe, NM' },
  { label: 'Welch, WV' },
  { label: 'Harrisburg, PA' },
  { label: 'Helena, MT' },
  { label: 'Lewiston, ME' },
  { label: 'Ashland, OH' },
  { label: 'Joplin, MO' },
  { label: 'Santa Rosa, CA' },
  { label: 'Leesburg, GA' },
  { label: 'Ladson, SC' },
  { label: 'Naples, FL' },
  { label: 'Rapid City, SD' },
  { label: 'Fontana, CA' },
  { label: 'Germantown, MD' },
  { label: 'Binghamton, NY' },
  { label: 'Rock Island, IL' },
  { label: 'Hartford, CT' },
  { label: 'Urbana, IL' },
  { label: 'Appleton, WI' },
  { label: 'Fowlerville, MI' },
  { label: 'Goose Creek, SC' },
  { label: 'Las Cruces, NM' },
  { label: 'Columbia, SC' },
  { label: 'Utica, NY' },
  { label: 'Newport, RI' },
  { label: 'Paterson, NJ' },
  { label: 'Concord, NH' },
  { label: 'Goldsboro, NC' },
  { label: 'Iowa City, IA' },
  { label: 'State College, PA' },
  { label: 'East Rutherford, NJ' },
  { label: 'Normal, IL' },
  { label: 'Lafayette, IN' },
  { label: 'Asheville, NC' },
  { label: 'Windsor, NS' },
  { label: 'Monterey, CA' },
  { label: 'Weatherford, TX' },
  { label: 'Morristown, TN' },
  { label: 'Browns Mills, NJ' },
  { label: 'Allegan, MI' },
  { label: 'Natick, MA' },
  { label: 'Plattsburgh, NY' },
  { label: 'Topeka, KS' },
  { label: 'Arlington, KY' },
  { label: 'Lancaster, PA' },
  { label: 'Farmington, MO' },
  { label: 'Albany, NY' },
  { label: 'Versailles, MO' },
  { label: 'Ojai, CA' },
  { label: 'Dayton, OH' },
  { label: 'Syracuse, NY' },
  { label: 'Roanoke, VA' },
  { label: 'Venice, FL' },
  { label: 'Greenville, SC' },
  { label: 'West Caldwell, NJ' },
  { label: 'Cottonwood, AZ' },
  { label: 'Fort Myers, FL' },
  { label: 'Springfield, MO' },
  { label: 'East Providence, RI' },
  { label: 'Wilmington, NC' },
  { label: 'Watkins Glen, NY' },
  { label: 'Peoria, AZ' },
  { label: 'Kerrville, TX' },
  { label: 'Neillsville, WI' },
  { label: 'Scranton, PA' },
  { label: 'Rutherford, NJ' },
  { label: 'Bolingbrook, IL' },
  { label: 'Vancouver, WA' },
  { label: 'Longview, TX' },
  { label: 'Woodstock, GA' },
  { label: 'Thousand Oaks, CA' },
  { label: 'Bowling Green, KY' },
  { label: 'Huntsville, AL' },
  { label: 'Augusta, ME' },
  { label: 'Redding, CA' },
  { label: 'Truro, NS' },
  { label: 'McHenry, IL' },
  { label: 'Bergen County, NJ' },
  { label: 'Walla Walla, WA' },
  { label: 'Paola, KS' },
  { label: 'Ann Arbor, MI' },
  { label: 'Ypsilanti, MI' },
  { label: 'Hope, AR' },
  { label: 'Port St Lucie, FL' },
  { label: 'Deerfield Beach, FL' },
  { label: 'Santa Barbara, CA' },
  { label: 'Rockford, IL' },
  { label: 'Challis, ID' },
  { label: 'Columbus, GA' },
  { label: 'Portageville, MO' },
  { label: 'Manchester, NH' },
  { label: 'Gainesville, GA' },
  { label: 'Winder, GA' },
  { label: 'Marietta, GA' },
  { label: 'Cumming, GA' },
  { label: 'Allentown, PA' },
  { label: 'Rockville, MD' },
  { label: 'Buford, GA' },
  { label: 'Saint George, UT' },
  { label: 'Indio, CA' },
  { label: 'Princeton, NJ' },
  { label: 'New Haven, CT' },
  { label: 'Macon, GA' },
  { label: 'Tupelo, MS' },
  { label: 'Belen, NM' },
  { label: 'Idaho Falls, ID' },
  { label: 'Olympia, WA' },
  { label: 'San Angelo, TX' },
  { label: 'Newport News, VA' },
  { label: 'Lexington, KY' },
  { label: 'Chico, CA' },
  { label: 'Tallahassee, FL' },
  { label: 'Fort Lauderdale, FL' },
  { label: 'Nashville, TN' },
  { label: 'Chevy Chase, MD' },
  { label: 'Towanda, PA' },
  { label: 'Saint Johns, MI' },
  { label: 'West Palm Beach, FL' },
  { label: 'New Paltz, NY' },
  { label: 'Roy, UT' },
  { label: 'Havana, IL' },
  { label: 'Leawood, KS' },
  { label: 'Tiffin, OH' },
  { label: 'Davenport, IA' },
  { label: 'Neenah, WI' },
  { label: 'Fairborn, OH' },
  { label: 'Athens, GA' },
  { label: 'Melbourne, AR' },
  { label: 'Odessa, TX' },
  { label: 'Westfield, MA' },
  { label: 'Hattiesburg, MS' },
  { label: 'McAllen, TX' },
  { label: 'Lexington Park, MD' },
  { label: 'Palmdale, CA' },
  { label: 'Northampton, MA' },
  { label: 'Johnstown, PA' },
  { label: 'Norwalk, CT' },
  { label: 'Herndon, VA' },
  { label: 'West Plains, MO' },
  { label: 'Hermosa Beach, CA' },
  { label: 'Palm Coast, FL' },
  { label: 'Watseka, IL' },
  { label: 'Batavia, IL' },
  { label: 'Bloomington, IN' },
  { label: 'Waco, TX' },
  { label: 'Oelwein, IA' },
  { label: 'Fredericksburg, VA' },
  { label: 'Wallingford, CT' },
  { label: 'Santa Clarita, CA' },
  { label: 'Plymouth, MI' },
  { label: 'Ashland, MA' },
  { label: 'Parsippany-Troy Hills, NJ' },
  { label: 'Woodbridge, NJ' },
  { label: 'Gadsden, AL' },
  { label: 'Stanford, CA' },
  { label: 'Bath, NY' },
  { label: 'Bremerton, WA' },
  { label: 'Hope Mills, NC' },
  { label: 'Duluth, MN' },
  { label: 'Eldon, MO' },
  { label: 'Brunswick, GA' },
  { label: 'Oxnard, CA' },
  { label: 'Blytheville, AR' },
  { label: 'Sioux Falls, SD' },
  { label: 'Springfield, MA' },
  { label: 'Kenosha, WI' },
  { label: 'Irvine, CA' },
  { label: 'Dennison, OH' },
  { label: 'Woodbury, NY' },
  { label: 'Barnegat, NJ' },
  { label: 'College Station, TX' },
  { label: 'Decatur, IL' },
  { label: 'Aurora, IL' },
  { label: 'Westminster, CA' },
  { label: 'Evansville, IN' },
  { label: 'Providence, RI' },
  { label: 'West Frankfort, IL' },
  { label: 'Springfield, IL' },
  { label: 'Kokomo, IN' },
  { label: 'Gardnerville, NV' },
  { label: 'Watertown, NY' },
  { label: 'Chattanooga, TN' },
  { label: 'Hanover, NH' },
  { label: 'Bellingham, WA' },
  { label: 'Tempe, AZ' },
  { label: 'Long Branch, NJ' },
  { label: 'Williamsburg, VA' },
  { label: 'Springfield, VA' },
  { label: 'Lawrenceville, GA' },
  { label: 'Saddle Brook, NJ' },
  { label: 'High Point, NC' },
  { label: 'Martha\'s Vineyard, MA' },
  { label: 'Texarkana, AR' },
  { label: 'Lawrence, KS' },
  { label: 'Westhampton Beach, NY' },
  { label: 'Marion, AR' },
  { label: 'De Witt, NE' },
  { label: 'Metro,Lampung' },
  { label: 'Charleston, SC' },
  { label: 'Fort Collins, CO' },
  { label: 'Baytown, TX' },
  { label: 'Tisdale, SK' },
  { label: 'Bridgewater, NS' },
  { label: 'Kingwood, WV' },
  { label: 'Lake Charles, LA' },
  { label: 'Paris, TX' },
  { label: 'Batesville, MS' },
  { label: 'Ventura, CA' },
  { label: 'Summersville, WV' },
  { label: 'Basin, WY' },
  { label: 'Medford, OR' },
  { label: 'Ridgecrest, CA' },
  { label: 'Fairfield, ME' },
  { label: 'Highland, CA' },
  { label: 'Wayland, NY' },
  { label: 'Wisconsin Dells, WI' },
  { label: 'Rogers, AR' },
  { label: 'Libertyville, IL' },
  { label: 'Zanesville, OH' },
  { label: 'Reading, PA' },
  { label: 'Balch Springs, TX' },
  { label: 'Middlesex, NJ' },
  { label: 'Fairfax, VA' },
  { label: 'Lahaina, HI' },
  { label: 'Royersford, PA' },
  { label: 'Marshfield, WI' },
  { label: 'Aspen, CO' },
  { label: 'Osceola, WI' },
  { label: 'Portland, ME' },
  { label: 'Carbondale, IL' },
  { label: 'Seaside Heights, NJ' },
  { label: 'Rochester, MN' },
  { label: 'Grand Forks, ND' },
  { label: 'Santa Cruz, CA' },
  { label: 'Fargo, ND' },
  { label: 'Wausau, WI' },
  { label: 'Crestline, CA' },
  { label: 'Woodbridge, VA' },
  { label: 'Morenci, AZ' },
  { label: 'Santa Monica, CA' },
  { label: 'Biloxi, MS' },
  { label: 'Clayton, GA' },
  { label: 'Broome, WA' },
  { label: 'Whitefield, ME' },
  { label: 'Hazard, KY' },
  { label: 'Spring Valley, IL' },
  { label: 'Manassas, VA' },
  { label: 'Stanfield, NC' },
  { label: 'East Orange, NJ' },
  { label: 'Williamsport, PA' },
  { label: 'Paso Robles, CA' },
  { label: 'Midland, MI' },
  { label: 'Mount Pleasant, MI' },
  { label: 'Martinsburg, WV' },
  { label: 'Melbourne, FL' },
  { label: 'Pensacola, FL' },
  { label: 'Alexandria, VA' },
  { label: 'Kalamazoo, MI' },
  { label: 'New Bedford, MA' },
  { label: 'Monroe, MI' },
  { label: 'Tega Cay, SC' },
  { label: 'Amherst, VA' },
  { label: 'West Chester, PA' },
  { label: 'Chesterfield, MI' },
  { label: 'Valparaiso, IN' },
  { label: 'Bradenton, FL' },
  { label: 'Albert Lea, MN' },
  { label: 'Marquette, MI' },
  { label: 'Trenton, NJ' },
  { label: 'Price, UT' },
  { label: 'Albany, OR' },
  { label: 'Tuscaloosa, AL' },
  { label: 'Shepherdstown, WV' },
  { label: 'Annapolis, MD' },
  { label: 'Sheboygan, WI' },
  { label: 'Pocatello, ID' },
  { label: 'Thorne Bay, AK' },
  { label: 'Kennewick, WA' },
  { label: 'Newport Beach, CA' },
  { label: 'Trumbull, CT' },
  { label: 'Danville, CA' },
  { label: 'Killeen, TX' },
  { label: 'Myrtle Beach, SC' },
  { label: 'Van Buren, AR' },
  { label: 'Greenbriar, AR' },
  { label: 'Geneva, IL' },
  { label: 'Laurel, MS' },
  { label: 'Crystal Lake, IL' },
  { label: 'Richmond, KY' },
  { label: 'Dothan, AL' },
  { label: 'Prescott, AZ' },
  { label: 'Erie, PA' },
  { label: 'Bismarck, ND' },
  { label: 'Batumi, Ajara' },
  { label: 'Mapleton, UT' },
  { label: 'Hagerstown, MD' },
  { label: 'Lumut, Perak' },
  { label: 'Ville Platte, LA' },
  { label: 'Fort Dodge, IA' },
  { label: 'Southampton, NY' },
  { label: 'Ames, IA' },
  { label: 'York, PA' },
  { label: 'Arlington, TX' },
  { label: 'Shamokin, PA' },
  { label: 'Prophetstown, IL' },
  { label: 'Sandwich, Kent' },
  { label: 'Red Bank, NJ' },
  { label: 'Silver Spring, MD' },
  { label: 'La Ronge, SK' },
  { label: 'Weinan, Shaanxi' },
  { label: 'Hamriyah, Ruwi' },
  { label: 'Cerritos, CA' },
  { label: 'Greenville, TX' },
  { label: 'Kunming, Yunnan' },
  { label: 'Mount Pleasant, PA' },
  { label: 'Ixtapa, JAL' },
  { label: 'Charlottesville, VA' },
  { label: 'West Hartford, CT' },
  { label: 'Jackson, WY' },
  { label: 'Youngstown, OH' },
  { label: 'London, KY' },
  { label: 'Morristown, NJ' },
  { label: 'Banning, CA' },
  { label: 'Sandakan, Sabah' },
  { label: 'Murfreesboro, TN' },
  { label: 'Augusta, GA' },
  { label: 'Eugene, OR' },
  { label: 'Klamath Falls, OR' },
  { label: 'Pomona, CA' },
  { label: 'Breckenridge, CO' },
  { label: 'Stillwater, OK' },
  { label: 'West Greenwich, RI' },
  { label: 'Fayetteville, NC' },
  { label: 'Anaconda, MT' },
  { label: 'Deer River, MN' },
  { label: 'Waynesville, MO' },
  { label: 'Alpena, MI' },
  { label: 'Ocala, FL' },
  { label: 'Amarillo, TX' },
  { label: 'Jonesboro, AR' },
  { label: 'Green Bay, WI' },
  { label: 'Brecksville, OH' },
  { label: 'Redmond, WA' },
  { label: 'Neosho, MO' },
  { label: 'Owensboro, KY' },
  { label: 'Rhinelander, WI' },
  { label: 'Flanders, NJ' },
  { label: 'Morrisville, PA' },
  { label: 'Bentonville, AR' },
  { label: 'Anderson, SC' },
  { label: 'Big Spring, TX' },
  { label: 'Dunellen, NJ' },
  { label: 'Adelanto, CA' },
  { label: 'Warner Robins, GA' },
  { label: 'Columbia, MO' },
  { label: 'Terre Haute, IN' },
  { label: 'Saint Clair (St Clair), MI' },
  { label: 'Perkasie, PA' },
  { label: 'Jacksonville, NC' },
  { label: 'Bowie, MD' },
  { label: 'Clearwater, FL' },
  { label: 'Whitinsville, Northbridge, MA' },
  { label: 'Brea, CA' },
  { label: 'Vallejo, CA' },
  { label: 'Spring Hill, FL' },
  { label: 'Bend, OR' },
  { label: 'Columbia, MD' },
  { label: 'Charleston, WV' },
  { label: 'Bradford, PA' },
  { label: 'Yuma, AZ' },
  { label: 'Waterloo, IA' },
  { label: 'Easton, MD' },
  { label: 'Shelby Township, MI' },
  { label: 'Winchester, VA' },
  { label: 'Smithtown, NY' },
  { label: 'Teriang, Pahang' },
  { label: 'Hilo, HI' },
  { label: 'Merrillville, IN' },
  { label: 'Coon Rapids, MN' },
  { label: 'Fayetteville, AR' },
  { label: 'Cartersville, GA' },
  { label: 'Woodville, MS' },
  { label: 'Beach Haven, NJ' },
  { label: 'Midland, TX' },
  { label: 'Missoula, MT' },
  { label: 'Waukesha, WI' },
  { label: 'Plymouth, IN' },
  { label: 'Pullman, WA' },
  { label: 'Albany, GA' },
  { label: 'Billings, MT' },
  { label: 'Cedar Rapids, IA' },
  { label: 'Campbellsville, KY' },
  { label: 'Sulphur Springs, TX' },
  { label: 'Worcester, MA' },
  { label: 'Costa Mesa, CA' },
  { label: 'Yorkville, IL' },
  { label: 'Simi Valley, CA' },
  { label: 'Beaverton, OR' },
  { label: 'Chelan, WA' },
  { label: 'Lima, OH' },
  { label: 'Lafayette, LA' },
  { label: 'Coeur d\'Alene, ID' },
  { label: 'Saint Cloud, MN' },
  { label: 'Muskegon, MI' },
  { label: 'Florence, AL' },
  { label: 'Greenwich, CT' },
  { label: 'Glasgow, MT' },
  { label: 'Verona, VA' },
  { label: 'Newton, MA' },
  { label: 'Montpelier, VT' },
  { label: 'Naperville, IL' },
  { label: 'Mountain View, CA' },
  { label: 'Howard, KS' },
  { label: 'Pleasanton, CA' },
  { label: 'Lafayette, CO' },
  { label: 'Marlborough, MA' },
  { label: 'Waycross, GA' },
  { label: 'South Yarmouth, MA' },
  { label: 'Paducah, KY' },
  { label: 'Atascadero, CA' },
  { label: 'Auburn, AL' },
  { label: 'Grandview, WA' },
  { label: 'Yuba City, CA' },
  { label: 'Conway, AR' },
  { label: 'Overland Park, KS' },
  { label: 'Dillingham, AK' },
  { label: 'Edison, NJ' },
  { label: 'North Platte, NE' },
  { label: 'Jackson, TN' },
  { label: 'Detroit Lakes, MN' },
  { label: 'Herrin, IL' },
  { label: 'Kearney, NE' },
  { label: 'San Luis Obispo, CA' },
  { label: 'Aberdeen, SD' },
  { label: 'Bemidji, MN' },
  { label: 'Roseburg, OR' },
  { label: 'Deltona, FL' },
  { label: 'Bismarck, AR' },
  { label: 'Kernersville, NC' },
  { label: 'Mount Vernon, NY' },
  { label: 'Laramie, WY' },
  { label: 'Peoria, IL' },
  { label: 'Centreville, VA' },
  { label: 'Statesboro, GA' },
  { label: 'San Marcos, TX' },
  { label: 'Gainesville, FL' },
  { label: 'Berkeley Heights, NJ' },
  { label: 'Vadnais Heights, MN' },
  { label: 'Berkeley, CA' },
  { label: 'Gulfport, MS' },
  { label: 'New Iberia, LA' },
  { label: 'Chapel Hill, NC' },
  { label: 'Spruce Pine, NC' },
  { label: 'Yanceyville, NC' },
  { label: 'New Bern, NC' },
  { label: 'Ripon, CA' },
  { label: 'Collinsville, IL' },
  { label: 'Lawton, OK' },
  { label: 'Amenia, NY' },
  { label: 'Brandon, MB' },
  { label: 'Wichita Falls, TX' },
  { label: 'London, OH' },
  { label: 'Orem, UT' },
  { label: 'Woodstock, NY' },
  { label: 'Ithaca, NY' },
  { label: 'Thomasville, GA' },
  { label: 'Kidron, OH' },
  { label: 'West Dundee, IL' },
  { label: 'Windsor, CT' },
  { label: 'Presque Isle, ME' },
  { label: 'Harlingen, TX' },
  { label: 'Topping, VA' },
  { label: 'Ryde, Isle of Wight' },
  { label: 'Alton, IL' },
  { label: 'Whitney, TX' },
  { label: 'Cape May Court House, NJ' },
  { label: 'Dickinson, ND' },
  { label: 'Panama City, FL' },
  { label: 'Brooklyn, NY' },
  { label: 'Willow Spring, NC' },
  { label: 'Rancho Palos Verdes, CA' },
  { label: 'Sydney, NS' },
  { label: 'Wyandotte, MI' },
  { label: 'Belvidere, IL' },
  { label: 'Bourne, MA' },
  { label: 'Fond du Lac, WI' },
  { label: 'Zeeland, MI' },
  { label: 'Everett, WA' },
  { label: 'Janesville, MN' },
  { label: 'Georgetown, DE' },
  { label: 'Abilene, TX' },
  { label: 'Bellevue, WA' },
  { label: 'Manistee, MI' },
  { label: 'Sheridan, WY' },
  { label: 'Lansing, MI' },
  { label: 'Teaneck, NJ' },
  { label: 'Wickliffe, OH' },
  { label: 'Queens, NY' },
  { label: 'Kelso, WA' },
  { label: 'Pembroke Pines, FL' },
  { label: 'Sarasota, FL' },
  { label: 'Woodburn, OR' },
  { label: 'Moose Jaw, SK' },
  { label: 'Carlsbad, NM' },
  { label: 'Pittsfield, MA' },
  { label: 'Kaunakakai, HI' },
  { label: 'Yakima, WA' },
  { label: 'San Dimas, CA' },
  { label: 'Crescent City, CA' },
  { label: 'Hayward, CA' },
  { label: 'Carthage, MO' },
  { label: 'Malott, WA' },
  { label: 'Woodland, WA' },
  { label: 'Auburndale, FL' },
  { label: 'Warren, PA' },
  { label: 'International Falls, MN' },
  { label: 'Cloquet, MN' },
  { label: 'New Port Richey, FL' },
  { label: 'La Crosse, WI' },
  { label: 'Wilmington, DE' },
  { label: 'Portsmouth, NH' },
  { label: 'Butte, MT' },
  { label: 'St. John\'s, NL' },
  { label: 'Martinsville, VA' },
  { label: 'Grass Valley, CA' },
  { label: 'Annapolis Valley, NS' },
  { label: 'Lakeville, MN' },
  { label: 'Hays, KS' },
  { label: 'Merrill, WI' },
  { label: 'Flagstaff, AZ' },
  { label: 'Tumwater, WA' },
  { label: 'Tenino, WA' },
  { label: 'Yelm, WA' },
  { label: 'Lacey, WA' },
  { label: 'Littlerock, WA' },
  { label: 'Auburn, WA' },
  { label: 'Lakewood, WA' },
  { label: 'Bucoda, WA' },
  { label: 'Centralia, WA' },
  { label: 'Puyallup, WA' },
  { label: 'Ocean Shores, WA' },
  { label: 'DuPont, WA' },
  { label: 'Enumclaw, WA' },
  { label: 'North Bend, WA' },
  { label: 'Longview, WA' },
  { label: 'Forks, WA' },
  { label: 'Rochester, WA' },
  { label: 'Aberdeen, WA' },
  { label: 'Buckley, WA' },
  { label: 'Airway Heights, WA' },
  { label: 'Chehalis, WA' },
  { label: 'Mount Vernon, WA' },
  { label: 'University Place, WA' },
  { label: 'Zillah, WA' },
  { label: 'Union Gap, WA' },
  { label: 'Tukwila, WA' },
  { label: 'Bainbridge Island, WA' },
  { label: 'Grand Coulee, WA' },
  { label: 'Gig Harbor, WA' },
  { label: 'Maytown, WA' },
  { label: 'Salem, OR' },
  { label: 'Electric City, WA' },
  { label: 'Arlington, WA' },
  { label: 'Algona, WA' },
  { label: 'SeaTac, WA' },
  { label: 'Shoreline, WA' },
  { label: 'Salina, KS' },
  { label: 'Xinyu, Jiangxi' },
  { label: 'Deerfield, IL' },
  { label: 'Shippensburg, PA' },
  { label: 'Patton, PA' },
  { label: 'Bayonne, NJ' },
  { label: 'Lake Geneva, WI' },
  { label: 'Zephyrhills, FL' },
  { label: 'Appomattox, VA' },
  { label: 'Rochester, MI' },
  { label: 'Upland, CA' },
  { label: 'Oshkosh, WI' },
  { label: 'Ashland, WI' },
  { label: 'Christiansburg, VA' },
  { label: 'Central Valley, NY' },
  { label: 'Manhattan, KS' },
  { label: 'Cheyenne, WY' },
  { label: 'Moscow, ID' },
  { label: 'Rancho Cucamonga, CA' },
  { label: 'Cambridge, MA' },
  { label: 'Rehoboth Beach, DE' },
  { label: 'Young Harris, GA' },
  { label: 'Hobbs, NM' },
  { label: 'Moline, IL' },
  { label: 'Douglasville, GA' },
  { label: 'Wakefield, MA' },
  { label: 'Greensburg, PA' },
  { label: 'Cherry Hill, NJ' },
  { label: 'Amargosa Valley, NV' },
  { label: 'Renton, WA' },
  { label: 'Montclair, NJ' },
  { label: 'Warrenton, VA' },
  { label: 'Atlantic City, NJ' },
  { label: 'Athens, OH' },
  { label: 'Morgantown, WV' },
  { label: 'Port Hadlock, WA' },
  { label: 'Lihue, HI' },
  { label: 'Bethesda, MD' },
  { label: 'Lakeport, CA' },
  { label: 'Leggett, CA' },
  { label: 'Kangar, Perlis' },
  { label: 'Reston, VA' },
  { label: 'Fort Atkinson, WI' },
  { label: 'Congers, NY' },
  { label: 'Cumberland, MD' },
  { label: 'Colby, KS' },
  { label: 'Melfort, SK' },
  { label: 'Saint Joseph, MO' },
  { label: 'Pagosa Springs, CO' },
  { label: 'Monterey Park, CA' },
  { label: 'Cumbum, Tamil Nadu' },
  { label: 'Heidelberg, GP' },
  { label: 'Pottsboro, TX' },
  { label: 'Mansfield, OH' },
  { label: 'Clifton, NJ' },
  { label: 'Tyler, TX' },
  { label: 'Minersville, PA' },
  { label: 'Ottumwa, IA' },
  { label: 'Ellsinore, MO' },
  { label: 'Cedar City, UT' },
  { label: 'Lombard, IL' },
  { label: 'Zion, IL' },
  { label: 'Southbridge, MA' },
  { label: 'Saginaw, MI' },
  { label: 'Bluffton, OH' },
  { label: 'Paris, AR' },
  { label: 'Nacogdoches, TX' },
  { label: 'McKinney, TX' },
  { label: 'Norwich, CT' },
  { label: 'Boulder, CO' },
  { label: 'Pikeville, KY' },
  { label: 'White Lake Township, MI' },
  { label: 'Palm Springs, CA' },
  { label: 'Moss Point, MS' },
  { label: 'Daytona Beach, FL' },
  { label: 'Galesburg, IL' },
  { label: 'Norwich, NY' },
  { label: 'Wesfield, NJ' },
  { label: 'Key West, FL' },
  { label: 'York, SC' },
  { label: 'Sunnyvale, CA' },
  { label: 'New Castle, PA' },
  { label: 'Iqaluit, NU' },
  { label: 'Casper, WY' },
  { label: 'Bar Harbor, ME' },
  { label: 'Victorville, CA' },
  { label: 'Clinton, IA' },
  { label: 'Summerville, SC' },
  { label: 'Greenville, NC' },
  { label: 'Shenandoah, IA' },
  { label: 'Carson, CA' },
  { label: 'Payson, AZ' },
  { label: 'Sun Valley, ID' },
  { label: 'Bozeman, MT' },
  { label: 'Wyomissing, PA' },
  { label: 'Middletown, NJ' },
  { label: 'Fairfield, CA' },
  { label: 'Fort Scott, KS' },
  { label: 'Adrian, MI' },
  { label: 'Ranger, TX' },
  { label: 'Lynchburg, VA' },
  { label: 'Pacific Palisades, CA' },
  { label: 'Avondale, AZ' },
  { label: 'Ponca City, OK' },
  { label: 'Visalia, CA' },
  { label: 'Mooresville, NC' },
  { label: 'Maui, HI' },
  { label: 'The Woodlands, TX' },
  { label: 'Bronx, NY' },
  { label: 'Bluefield, WV' },
  { label: 'Alamos, Sonora' },
  { label: 'North East, MD' },
  { label: 'Lancaster, CA' },
  { label: 'Jonesboro, LA' },
  { label: 'Beckley, WV' },
  { label: 'Des Plaines, IL' },
  { label: 'Honesdale, PA' },
  { label: 'Johnson City, TN' },
  { label: 'Nashua, NH' },
  { label: 'College Park, MD' },
  { label: 'Staples, MN' },
  { label: 'Willmar, MN' },
  { label: 'Waikiki, HI' },
  { label: 'New Milford, CT' },
  { label: 'Victoria, TX' },
  { label: 'Mansfield, CT' },
  { label: 'Palo Alto, CA' },
  { label: 'Jeffersonville, IN' },
  { label: 'Huntington Woods, MI' },
  { label: 'Westborough, MA' },
  { label: 'Flint, MI' },
  { label: 'Carson City, NV' },
  { label: 'Pontotoc, MS' },
  { label: 'Scotch Plains, NJ' },
  { label: 'Crete, NE' },
  { label: 'Summerside, PE' },
  { label: 'Aurora, CO' },
  { label: 'Laurel, MD' },
  { label: 'Belton, SC' },
  { label: 'Great Falls, MT' },
  { label: 'Queen Creek, AZ' },
  { label: 'Hickory, NC' },
  { label: 'Surprise, AZ' },
  { label: 'Beaumont, TX' },
  { label: 'Richfield, MN' },
  { label: 'Farmington, NM' },
  { label: 'Buffalo, MN' },
  { label: 'Seaside, OR' },
  { label: 'Tooele, UT' },
  { label: 'Campbellton, NB' },
  { label: 'Newark, DE' },
  { label: 'Langley, WA' },
  { label: 'Milford, PA' },
  { label: 'Passaic, NJ' },
  { label: 'Allston, MA' },
  { label: 'Seward, AK' },
  { label: 'Camden, NJ' },
  { label: 'New Braunfels, TX' },
  { label: 'Northfield, MN' },
  { label: 'West Chazy, NY' },
  { label: 'Houston, MO' },
  { label: 'Highland, IL' },
  { label: 'Rocky Point, NY' },
  { label: 'Elkhart, IN' },
  { label: 'Valdosta, GA' },
  { label: 'Canton, OH' },
  { label: 'Cutler Bay, FL' },
  { label: 'Fairbanks, AK' },
  { label: 'Macon, MO' },
  { label: 'Cupertino, CA' },
  { label: 'Franklin, TN' },
  { label: 'Traverse City, MI' },
  { label: 'Gillette, WY' },
  { label: 'Eureka, CA' },
  { label: 'Scottsville, KY' },
  { label: 'Moncks Corner, SC' },
  { label: 'Millington, MI' },
  { label: 'North Charleston, SC' },
  { label: 'Brandon, VT' },
  { label: 'Lakeland, FL' },
  { label: 'Shawnee, OK' },
  { label: 'Boca Raton, FL' },
  { label: 'Folkston, GA' },
  { label: 'East Lansing, MI' },
  { label: 'Santa Rosa Beach, FL' },
  { label: 'Belleville, IL' },
  { label: 'Kodiak, AK' },
  { label: 'Holly Springs, NC' },
  { label: 'Coachella, CA' },
  { label: 'Logan, UT' },
  { label: 'Seven Points, TX' },
  { label: 'Waldorf, MD' },
  { label: 'New Smyrna Beach, FL' },
  { label: 'Burlington, KY' },
  { label: 'Mount Shasta, CA' },
  { label: 'Clay County, WV' },
  { label: 'Oceanside, CA' },
  { label: 'Cabot, AR' },
  { label: 'Tustin, CA' },
  { label: 'Hamilton, OH' },
  { label: 'Grand Junction, CO' },
  { label: 'Hoboken, NJ' },
  { label: 'Merced, CA' },
  { label: 'Chandler, AZ' },
  { label: 'East Chicago, IN' },
  { label: 'Waynesboro, PA' },
  { label: 'Kingsport, TN' },
  { label: 'Highlands, NC' },
  { label: 'Taos, NM' },
  { label: 'Wixom, MI' },
  { label: 'Coos Bay, OR' },
  { label: 'Laredo, TX' },
  { label: 'Buffalo Grove, IL' },
  { label: 'Spartanburg, SC' },
  { label: 'Western Grove, AR' },
  { label: 'Franklin Park, IL' },
  { label: 'Kinston, NC' },
  { label: 'Salisbury, MD' },
  { label: 'Maryville, MO' },
  { label: 'Gloucester, MA' },
  { label: 'Troy, AL' },
  { label: 'Topsham, ME' },
  { label: 'Waterbury, CT' },
  { label: 'Hermiston, OR' },
  { label: 'Farmville, VA' },
  { label: 'Lockport, IL' },
  { label: 'Wauwatosa, WI' },
  { label: 'Jackson, NJ' },
  { label: 'Martinez, CA' },
  { label: 'Queensbury, NY' },
  { label: 'Cornelius, NC' },
  { label: 'O\'Fallon, IL' },
  { label: 'Kissimmee, FL' },
  { label: 'Toccoa Falls, GA' },
  { label: 'Downingtown, PA' },
  { label: 'Marathon, FL' },
  { label: 'New Windsor, NY' },
  { label: 'Allen, TX' },
  { label: 'Cranford, NJ' },
  { label: 'Canton, MA' },
  { label: 'Somerset, NJ' },
  { label: 'Yucca Valley, CA' },
  { label: 'Glendora, CA' },
  { label: 'Walnut, CA' },
  { label: 'Seymour, CT' },
  { label: 'The Villages, FL' },
  { label: 'Hoosick Falls, NY' },
  { label: 'Mentor, OH' },
  { label: 'Bloomington, IL' },
  { label: 'Moab, UT' },
  { label: 'Ixtapa, Guerrero' },
  { label: 'Kingston, NY' },
  { label: 'West Orange, NJ' },
  { label: 'Mission Viejo, CA' },
  { label: 'Farmington Hills, MI' },
  { label: 'Argos, IN' },
  { label: 'Troy, NY' },
  { label: 'Fairview, OR' },
  { label: 'Albrightsville, PA' },
  { label: 'Cape Girardeau, MO' },
  { label: 'Temecula, CA' },
  { label: 'Beeville, TX' },
  { label: 'Brownsville, TX' },
  { label: 'Marble Falls, TX' },
  { label: 'Massapequa Park, NY' },
  { label: 'Westerville, OH' },
  { label: 'Houghton, MI' },
  { label: 'Woodstock, IL' },
  { label: 'DeKalb, IL' },
  { label: 'Burlington, IA' },
  { label: 'Redwood Falls, MN' },
  { label: 'Montevallo, AL' },
  { label: 'Beloit, WI' },
  { label: 'Ardmore, OK' },
  { label: 'Alpharetta, GA' },
  { label: 'La Mesa, CA' },
  { label: 'Watsonville, CA' },
  { label: 'Mullica Hill, NJ' },
  { label: 'Westport, CT' },
  { label: 'Seaside Heights, NJ' },
  { label: 'Desert Hot Springs, CA' },
  { label: 'Woonsocket, RI' },
  { label: 'Lewiston, ID' },
  { label: 'Ravenswood, WV' },
  { label: 'Isla Vista, CA' },
  { label: 'Holderness, NH' },
  { label: 'Bear, DE' },
  { label: 'Durant, OK' },
  { label: 'Sumter, SC' },
  { label: 'Harrington Park, NJ' },
  { label: 'Valley Center, CA' },
  { label: 'Troy, MI' },
  { label: 'Loveland, CO' },
  { label: 'Arlington Heights, IL' },
  { label: 'Cary, NC' },
  { label: 'Apopka, FL' },
  { label: 'Clearfield, PA' },
  { label: 'Woodbine, GA' },
  { label: 'Marina, CA' },
  { label: 'American Canyon, CA' },
  { label: 'Sanford, NC' },
  { label: 'Middletown, CT' },
  { label: 'West Deptford, NJ' },
  { label: 'Turlock, CA' },
  { label: 'Willingboro, NJ' },
  { label: 'Alexandria, MN' },
  { label: 'Bedminster Township, NJ' },
  { label: 'Astoria, NY' },
  { label: 'Novi, MI' },
  { label: 'Torrington, CT' },
  { label: 'Spring Lake, NJ' },
  { label: 'Douglas, GA' },
  { label: 'Henderson, NV' },
  { label: 'Andover, MA' },
  { label: 'Luverne, AL' },
  { label: 'San Fernando, La Union' },
  { label: 'Santa Rosa, Las Lisas' },
  { label: 'Bourbonnais, IL' },
  { label: 'Saint Charles, MO' },
  { label: 'Eau Claire, WI' },
  { label: 'Great Barrington, MA' },
  { label: 'Seminole, FL' },
  { label: 'Webster, NY' },
  { label: 'Corcoran, CA' },
  { label: 'Proctor, MN' },
  { label: 'Clarksville, TN' },
  { label: 'Rocky Hill, CT' },
  { label: 'West Hollywood, CA' },
  { label: 'Hazel Park, MI' },
  { label: 'Southfield, MI' },
  { label: 'Pontiac, MI' },
  { label: 'Lompoc, CA' },
  { label: 'Newport, OR' },
  { label: 'Schaumburg, IL' },
  { label: 'Schererville, IN' },
  { label: 'Palmer, AK' },
  { label: 'Delray Beach, FL' },
  { label: 'Poughkeepsie, NY' },
  { label: 'Massapequa, NY' },
  { label: 'Manalapan Township, NJ' },
  { label: 'Fort Bragg, NC' },
  { label: 'Ogden, UT' },
  { label: 'Pasco, WA' },
  { label: 'Saratoga, CA' },
  { label: 'Hollywood, FL' },
  { label: 'Bethlehem, PA' },
  { label: 'Lexington, NE' },
  { label: 'Hilton, NY' },
  { label: 'Boron, CA' },
  { label: 'Radcliff, KY' },
  { label: 'Liberty, MO' },
  { label: 'Barrington, IL' },
  { label: 'Kent, WA' },
  { label: 'Belmont, CA' },
  { label: 'Eldersburg, MD' },
  { label: 'Sunny Isles Beach, FL' },
  { label: 'Waccabuc, NY' },
  { label: 'Marion, VA' },
  { label: 'Ducktown, TN' },
  { label: 'Garden Grove, CA' },
  { label: 'Coalville, UT' },
  { label: 'Whidbey Island, WA' },
  { label: 'Apple Valley, CA' },
  { label: 'Huntington Park, CA' },
  { label: 'San Rafael, CA' },
  { label: 'Rocklin, CA' },
  { label: 'Lindsay, OK' },
  { label: 'Medford, NY' },
  { label: 'Wakefield-Peacedale, RI' },
  { label: 'Cle Elum, WA' },
  { label: 'Grafton, WI' },
  { label: 'DeLand, FL' },
  { label: 'Ketchikan, AK' },
  { label: 'Clovis,  NM' },
  { label: 'Fairfield, CT' },
  { label: 'Leesville, LA' },
  { label: 'Concord, NC' },
  { label: 'Moultrie, GA' },
  { label: 'Crookston, MN' },
  { label: 'White Plains, NY' },
  { label: 'San Mateo, CA' },
  { label: 'Sequim, WA' },
  { label: 'Mill Spring, NC' },
  { label: 'Woodward,OK' },
  { label: 'Niles, MI' },
  { label: 'Millinocket, ME' },
  { label: 'Chesilhurst, NJ' },
  { label: 'Coral Springs, FL' },
  { label: 'Vero Beach, FL' },
  { label: 'Minot, ND' },
  { label: 'Brenham, TX' },
  { label: 'Hyattsville, MD' },
  { label: 'Williston, ND' },
  { label: 'Pinconning, MI' },
  { label: 'Lisle, IL' },
  { label: 'Tuscumbia, AL' },
  { label: 'Stroudsburg, PA' },
  { label: 'Sebring, FL' },
  { label: 'Sterling Heights, MI' },
  { label: 'Crestview, FL' },
  { label: 'Harper Woods, MI' },
  { label: 'Lathrop, CA' },
  { label: 'Livingston, TX' },
  { label: 'Port Jefferson Station, NY' },
  { label: 'Winter Haven, FL' },
  { label: 'Temple, TX' },
  { label: 'Stone Mountain, GA' },
  { label: 'Batavia, OH' },
  { label: 'Edgewood, NM' },
  { label: 'Bodega Bay, CA' },
  { label: 'Macomb, MI' },
  { label: 'Gonzales, LA' },
  { label: 'Cookeville, TN' },
  { label: 'Rocky Mount, NC' },
  { label: 'Pisgah, AL' },
  { label: 'Wooster, OH' },
  { label: 'South Hadley, MA' },
  { label: 'Zurich, MT' },
  { label: 'Polson, MT' },
  { label: 'Germantown, TN' },
  { label: 'Ukiah, CA' },
  { label: 'Gilroy, CA' },
  { label: 'Ballston, NY' },
  { label: 'Edwardsville, IL' },
  { label: 'Derry, NH' },
  { label: 'Selinsgrove, PA' },
  { label: 'Torrance, CA' },
  { label: 'Roseville, CA' },
  { label: 'Sitka, AK' },
  { label: 'Abingdon, MD' },
  { label: 'Erlanger, KY' },
  { label: 'Ridgefield, CT' },
  { label: 'Falmouth, MA' },
  { label: 'Caldwell, TX' },
  { label: 'McLean, VA' },
  { label: 'Peachtree City, GA' },
  { label: 'Pasadena, CA' },
  { label: 'Wayne, PA' },
  { label: 'Medford, MA' },
  { label: 'Bridgeton, NJ' },
  { label: 'Weston, CT' },
  { label: 'Conroe, TX' },
  { label: 'Ronkonkoma, NY' },
  { label: 'Pukalani, HI' },
  { label: 'Dahlonega, GA' },
  { label: 'Jackson, CA' },
  { label: 'Durango, CO' },
  { label: 'Pinellas Park, FL' },
  { label: 'New City, NY' },
  { label: 'Columbus, IN' },
  { label: 'Lebanon, OH' },
  { label: 'Parma, OH' },
  { label: 'Champaign, IL' },
  { label: 'Oxford, MS' },
  { label: 'Webb City, MO' },
  { label: 'Davis, CA' },
  { label: 'Kahului, HI' },
  { label: 'Kailua, HI' },
  { label: 'Makakilo, HI' },
  { label: 'Pearl City, HI' },
  { label: 'Santa Clara, CA' },
  { label: 'Waipahu, HI' },
  { label: 'Hampton, VA' },
  { label: 'Dover, DE' },
  { label: 'South Bend, IN' },
  { label: 'Lewisburg, PA' },
  { label: 'Redwood City, CA' },
  { label: 'Napa, CA' },
  { label: 'Twin Falls, ID' },
  { label: 'Burley, ID' },
  { label: 'Rock Springs, WY' },
  { label: 'El Centro, CA' },
  { label: 'Cherokee Village, AR' },
  { label: 'Groton, CT' },
  { label: 'Waterford, MI' },
  { label: 'Yale, MI' },
  { label: 'Elko, NV' },
  { label: 'Ankeny, IA' },
  { label: 'Somerville, MA' },
  { label: 'Vermillion, SD' },
  { label: 'Duluth, GA' },
  { label: 'Dover, NH' },
  { label: 'North Brunswick, NJ' },
  { label: 'Livermore, CA' },
  { label: 'Blacksburg, VA' },
  { label: 'Libby, MT' },
  { label: 'Bellevue, NE' },
  { label: 'Springfield, OR' },
  { label: 'Peekskill, NY' },
  { label: 'Brunswick, ME' },
  { label: 'Frisco, TX' },
  { label: 'Holland, MI' },
  { label: 'Suwanee, GA' },
  { label: 'Danbury, CT' },
  { label: 'Enterprise, Al' },
  { label: 'Ellsworth, ME' },
  { label: 'Hamburg, PA' },
  { label: 'Livonia, MI' },
  { label: 'Lewis Center, OH' },
  { label: 'Sheldon, IA' },
  { label: 'Elkins, WV' },
  { label: 'Encinitas, CA' },
  { label: 'Ford City, PA' },
  { label: 'Galveston, TX' },
  { label: 'Buckhead, GA' },
  { label: 'Avon, CO' },
  { label: 'Astoria, OR' },
  { label: 'Solon, OH' },
  { label: 'Murrieta, CA' },
  { label: 'Juneau, AK' },
  { label: 'Eden Prairie, MN' },
  { label: 'Carmel By The Sea, CA' },
  { label: 'Muskogee, OK' },
  { label: 'East Northport, NY' },
  { label: 'Waynesboro, VA' },
  { label: 'Frederick, MD' },
  { label: 'Los Gatos, CA' },
  { label: 'Yukon, OK' },
  { label: 'La Porte, IN' },
  { label: 'Fort Walton Beach, FL' },
  { label: 'Warren, MI' },
  { label: 'Big Rapids, MI' },
  { label: 'South Riding, VA' },
  { label: 'Chantilly, VA' },
  { label: 'Fort Smith, AR' },
  { label: 'Sand Point, AK' },
  { label: 'Eliot, ME' },
  { label: 'Woodinville, WA' },
  { label: 'Clayton, MO' },
  { label: 'Denton, TX' },
  { label: 'Oak Park, IL' },
  { label: 'Rochester, IL' },
  { label: 'Sedalia, MO' },
  { label: 'New Rochelle, NY' },
  { label: 'Alamogordo, NM' },
  { label: 'Cullman, AL' },
  { label: 'Amherst, NY' },
  { label: 'Doylestown, PA' },
  { label: 'Hyannis, MA' },
  { label: 'Poplarville, MS' },
  { label: 'Willimantic, CT' },
  { label: 'Kenyon, MN' },
  { label: 'Salem, IN' },
  { label: 'Meadville, PA' },
  { label: 'Grapevine, TX' },
  { label: 'Malvern, PA' },
  { label: 'Essex, CT' },
  { label: 'Lake View, IA' },
  { label: 'Taylor, TX' },
  { label: 'Rock Hill, SC' },
  { label: 'Claremore, OK' },
  { label: 'Athens, ME' },
  { label: 'Kirksville, MO' },
  { label: 'Kathleen, GA' },
  { label: 'Mound, MN' },
  { label: 'Richboro, PA' },
  { label: 'Hinesville, GA' },
  { label: 'Owosso, MI' },
  { label: 'North Attleborough, MA' },
  { label: 'Sioux City, IA' },
  { label: 'Rice Lake, WI' },
  { label: 'Kaneohe, HI' },
  { label: 'Bowling Green, OH' },
  { label: 'Geneva, NY' },
  { label: 'Massena, NY' },
  { label: 'Fishkill, NY' },
  { label: 'St. Charles, IL' },
  { label: 'Twinsburg, OH' },
  { label: 'Clarkton, MI' },
  { label: 'Cape Canaveral, FL' },
  { label: 'Longmont, CO' },
  { label: 'Gaylord, MI' },
  { label: 'Brainerd, MN' },
  { label: 'Athens, IL' },
  { label: 'Roseau, MN' },
  { label: 'Winnemucca, NV' },
  { label: 'Barrow, AK' },
  { label: 'Dublin, OH' },
  { label: 'Sewell, Mantua Township, NJ' },
  { label: 'Brattleboro, VT' },
  { label: 'Redlands, CA' },
  { label: 'Pendleton, OR' },
  { label: 'Pass Christian, MS' },
  { label: 'Monument, CO' },
  { label: 'Beverly Hills, CA' },
  { label: 'Lincoln, MO' },
  { label: 'West New York, NJ' },
  { label: 'Llano, TX' },
  { label: 'Morden, MB' },
  { label: 'Santa Maria, CA' },
  { label: 'Kalispell, MT' },
  { label: 'Del Rio, TX' },
  { label: 'Texarkana, TX' },
  { label: 'Katy, TX' },
  { label: 'Lomita, CA' },
  { label: 'Manahawkin, NJ' },
  { label: 'Pueblo, CO' },
  { label: 'Middletown, DE' },
  { label: 'Carlsbad, CA' },
  { label: 'Mankato, MN' },
  { label: 'Palatka, FL' },
  { label: 'Agoura Hills, CA' },
  { label: 'Monticello, UT' },
  { label: 'Canaan, NH' },
  { label: 'Lake Orion, MI' },
  { label: 'Rogers City, MI' },
  { label: 'Sun City Center, FL' },
  { label: 'Strasburg, VA' },
  { label: 'Lewisburg, TN' },
  { label: 'Alexandria, LA' },
  { label: 'Coldwater, MI' },
  { label: 'Chester, PA' },
  { label: 'Forest Park, GA' },
  { label: 'Westminster, MD' },
  { label: 'Lawrence, MA' },
  { label: 'Forsyth, MT' },
  { label: 'Freehold, NJ' },
  { label: 'Marshall, MN' },
  { label: 'Perth Amboy, NJ' },
  { label: 'Itabuna, Bahia' },
  { label: 'Grosse Pointe Woods, MI' },
  { label: 'Gettysburg, PA' },
  { label: 'Kings Park, NY' },
  { label: 'Crown Point, IN' },
  { label: 'Decorah, IA' },
  { label: 'Fred, TX' },
  { label: 'Minden, LA' },
  { label: 'Fortuna, CA' },
  { label: 'Oconto Falls, WI' },
  { label: 'St. Albans Town, VT' },
  { label: 'Yreka, CA' },
  { label: 'Anderson, IN' },
  { label: 'Media, PA' },
  { label: 'Bullhead City, AZ' },
  { label: 'Banting, Selangor' },
  { label: 'Hallandale Beach, FL' },
  { label: 'Levittown, NY' },
  { label: 'Battle Creek, MI' },
  { label: 'Manchester Township, NJ' },
  { label: 'Cape Carteret, NC' },
  { label: 'Saint Joseph, MI' },
  { label: 'Corning, NY' },
  { label: 'Mitchell, IN' },
  { label: 'Lehi, UT' },
  { label: 'Highlands Ranch, CO' },
  { label: 'Township of Dixville, NH' },
  { label: 'Longmeadow, MA' },
  { label: 'Fullerton, CA' },
  { label: 'Glen Cove, NY' },
  { label: 'Monroe, LA' },
  { label: 'Sterling, IL' },
  { label: 'Norwalk, CA' },
  { label: 'Glen Rose, TX' },
  { label: 'Andover, MN' },
  { label: 'Norman, OK' },
  { label: 'Erdenheim, PA' },
  { label: 'Warren, NJ' },
  { label: 'Salem, NH' },
  { label: 'Cody, WY' },
  { label: 'Milton, FL' },
  { label: 'Lemmon, SD' },
  { label: 'Oakland, TN' },
  { label: 'River Rouge, MI' },
  { label: 'Mountain House, CA' },
  { label: 'Taunton, MA' },
  { label: 'Wauseon, OH' },
  { label: 'Sevierville, TN' },
  { label: 'Oroville, CA' },
  { label: 'Canon City, CO' },
  { label: 'Sunrise, FL' },
  { label: 'Celina, OH' },
  { label: 'Mission, TX' },
  { label: 'The Dalles, OR' },
  { label: 'Slidell, LA' },
  { label: 'Sandusky, OH' },
  { label: 'Ashland, AL' },
  { label: 'Athens, TN' },
  { label: 'Battlement Mesa, CO' },
  { label: 'Beaver Dam, WI' },
  { label: 'Bishop, CA' },
  { label: 'Boone, NC' },
  { label: 'Burns, OR' },
  { label: 'Cadillac, MI' },
  { label: 'Candor, NC' },
  { label: 'Colusa, CA' },
  { label: 'Cortina Indian Rancheria, CA' },
  { label: 'Dale, IN' },
  { label: 'Decatur, AL' },
  { label: 'Dyersburg, TN' },
  { label: 'El Dorado, AR' },
  { label: 'Emmetsburg, IA' },
  { label: 'Florence, SC' },
  { label: 'Grand Island, NE' },
  { label: 'Grants Pass, OR' },
  { label: 'Hamilton, MT' },
  { label: 'Hammond, LA' },
  { label: 'Harriman, TN' },
  { label: 'Houma, LA' },
  { label: 'Jamesville, NC' },
  { label: 'Jasper, IN' },
  { label: 'Kenansville, NC' },
  { label: 'Lakeview, Lake County, OR' },
  { label: 'Lawrenceburg, TN' },
  { label: 'Lumberton, NC' },
  { label: 'Madera, CA' },
  { label: 'Marshall, TX' },
  { label: 'McAlester, OK' },
  { label: 'Mena, AR' },
  { label: 'Middlesborough, KY' },
  { label: 'Muscatine, IA' },
  { label: 'New Castle, IN' },
  { label: 'Parkersburg, WV' },
  { label: 'Portola, CA' },
  { label: 'Portsmouth, OH' },
  { label: 'Prineville, OR' },
  { label: 'Quincy, CA' },
  { label: 'Sandersville,Washington,GA' },
  { label: 'Sierra Vista, AZ' },
  { label: 'Sinclair, WY' },
  { label: 'Somerset, KY' },
  { label: 'Stuttgart, AR' },
  { label: 'Talladega, AL' },
  { label: 'Weirton, WV' },
  { label: 'Wenden, AZ' },
  { label: 'Winona, MN' },
  { label: 'Bolinas, CA' },
  { label: 'Baywood-Los Osos, CA' },
  { label: 'Arroyo Grande, CA' },
  { label: 'Bangor, ME' },
  { label: 'Nags Head, NC' },
  { label: 'Swampscott, MA' },
  { label: 'Issaquah, WA' },
  { label: 'Eagle, TX' },
  { label: 'Schenectady, NY' },
  { label: 'Saratoga Springs, NY' },
  { label: 'Independence, MO' },
  { label: 'Concord, CA' },
  { label: 'Walnut Creek, CA' },
  { label: 'Pierre, SD' },
  { label: 'Brookfield, MO' },
  { label: 'East Wenatchee, WA' },
  { label: 'Weaver, AL' },
  { label: 'Elizabethtown, KY' },
  { label: 'Pinehurst, NC' },
  { label: 'Bridgewater, NJ' },
  { label: 'Bristol, VA' },
  { label: 'East Freedom, PA' },
  { label: 'Sherman, TX' },
  { label: 'The Pas, MB' },
  { label: 'Springfield, NJ' },
  { label: 'Amherst, MA' },
  { label: 'Hugoton, KS' },
  { label: 'Seneca Falls, NY' },
  { label: 'Allendale, NJ' },
  { label: 'Ontario,CA' },
  { label: 'Angola, IN' },
  { label: 'Meadow Lake, SK' },
  { label: 'Moses Lake, WA' },
  { label: 'Lebanon, KY' },
  { label: 'Yucaipa, CA' },
  { label: 'Fort Drum, NY' },
  { label: 'Florence, KY' },
  { label: 'Nome, AK' },
  { label: 'Staten Island, NY' },
  { label: 'Paradise, CA' },
  { label: 'New Albany, OH' },
  { label: 'Ocean Springs, MI' },
  { label: 'Crestone, CO' },
  { label: 'Lake Worth, FL' },
  { label: 'Elizabethtown, NC' },
  { label: 'Ormond, VIC' },
  { label: 'Dodge City, KS' },
  { label: 'Mandeville, LA' },
  { label: 'North Aurora, IL' },
  { label: 'Bay Minette, AL' },
  { label: 'Eastpointe, MI' },
  { label: 'Bridgeport, CT' },
  { label: 'East St Louis, IL' },
  { label: 'Duvall, WA' },
  { label: 'Sylvania, OH' },
  { label: 'Summit, NJ' },
  { label: 'Anderson, CA' },
  { label: 'Sidney, NE' },
  { label: 'Corbin, KY' },
  { label: 'Oak Ridge, TN' },
  { label: 'Jupiter, FL' },
  { label: 'Thornton, CO' },
  { label: 'Ash Flat, AR' },
  { label: 'Redondo Beach, CA' },
  { label: 'Chesterfield, MO' },
  { label: 'Livingston Manor, NY' },
  { label: 'River Falls, WI' },
  { label: 'Cairo, IL' },
  { label: 'Diamond Bar, CA' },
  { label: 'Stephenville, TX' },
 
];



function renderInputComponent(inputProps) {
  const { classes, inputRef = () => {}, ref, ...other } = inputProps;

  return (
    <TextField
      variant="outlined"
      InputProps={{
        inputRef: node => {
          ref(node);
          inputRef(node);
        },
        classes: {
          input: classes.input,
        },
      }}
      {...other}
    />
  );
}

function renderSuggestion(suggestion, { query, isHighlighted }) {
  const matches = match(suggestion.label, query);
  const parts = parse(suggestion.label, matches);

  return (
    <MenuItem selected={isHighlighted} component="div">
      <div>
        {parts.map((part, index) =>
          part.highlight ? (
            <span key={String(index)} style={{ fontWeight: 500 }}>
              {part.text}
            </span>
          ) : (
            <strong key={String(index)} style={{ fontWeight: 300 }}>
              {part.text}
            </strong>
          ),
        )}
      </div>
    </MenuItem>
  );
}

export function getSuggestions(value) {
  const inputValue = deburr(value.trim()).toLowerCase();
  const inputLength = inputValue.length;
  let count = 0;
  if (value === '') return [];
  return inputLength === 0
    ? []
    : suggestions.filter(suggestion => {
        const keep =
          count < 5 && suggestion.label.slice(0, inputLength).toLowerCase() === inputValue;

        if (keep) {
          count += 1;
        }

        return keep;
      });
}

function getSuggestionValue(suggestion) {
  return suggestion.label;
}

const styles = theme => ({
  root: {
    flexGrow: 1,
  },
  container: {
    position: 'relative',
  },
  suggestionsContainerOpen: {
    position: 'absolute',
    zIndex: 1,
    marginTop: theme.spacing.unit,
    left: 0,
    right: 0,
  },
  suggestion: {
    display: 'block',
  },
  suggestionsList: {
    margin: 0,
    padding: 0,
    listStyleType: 'none',
  },
 
});

class IntegrationAutosuggest extends React.Component {
  constructor(props) {
    super(props);
    
    this.state = {
      location: this.props.location || '',
      suggestions: [],
      updated: this.props.profile || false
    };
  }

  componentDidUpdate = (prevProps, prevState) => {
    if (prevState.location !== this.props.location && !this.state.updated && this.props.location !== '')
    this.setState({
      location: this.props.location,
      updated: true
    });
  }

  handleSuggestionsFetchRequested = ({ value }) => {
    this.setState({
      suggestions: getSuggestions(value),
    });
  };

  handleSuggestionsClearRequested = () => {
    this.setState({
      suggestions: [],
    });
  };

  handleChange = (event, { newValue }) => {
      this.props.handler(newValue);
      this.setState({
        location: newValue,
      });
  };

  render() {
    const { classes } = this.props;

    const autosuggestProps = {
      renderInputComponent,
      suggestions: this.state.suggestions,
      onSuggestionsFetchRequested: this.handleSuggestionsFetchRequested,
      onSuggestionsClearRequested: this.handleSuggestionsClearRequested,
      getSuggestionValue,
      renderSuggestion,
    };

    return (
      <div className={classes.root}>
        <Autosuggest
          {...autosuggestProps}
          inputProps={{
            classes,
            placeholder: 'City*',
            value: this.state.location,
            onChange: this.handleChange,
          }}
          theme={{
            container: classes.container,
            suggestionsContainerOpen: classes.suggestionsContainerOpen,
            suggestionsList: classes.suggestionsList,
            suggestion: classes.suggestion,
          }}
          renderSuggestionsContainer={options => (
            <Paper {...options.containerProps} square>
              {options.children}
            </Paper>
          )}
        />
      </div>
    );
  }
}

IntegrationAutosuggest.propTypes = {
  classes: PropTypes.object.isRequired,
};

export default withStyles(styles)(IntegrationAutosuggest);